name = "duel-games"
main = "src/worker.ts"
compatibility_date = "2026-01-01"

[durable_objects]
bindings = [
  { name = "LOBBY", class_name = "Lobby" }
]

[[migrations]]
tag = "v3"
new_classes = ["Lobby"]
